#  Make sure the meet operator doesn't always assume static variables are live;
#  * they're only generated by uses, function calls, and EXIT.
#  * Test this using a program that never reaches EXIT (but does terminate
#  * by caling the exit function indirectly)
#  * 

pub fn exit_wrapper(status: i32) i32; #  defined in chapter_19/libraries/exit.c

pub i: i32;

pub fn target(none) i32 {
    i = 30 #  dead store!
    #  i isn't killed in this block but it's killed on all paths to function
    #  call
    counter: i32 = 0

    loop .. while true {
        if counter < 10 {
            i = counter + 1
        }
        else {
            i = counter + 2
        }
        if counter > 20 {
            exit_wrapper(i)
        }
        counter = counter + 1
    }
    return 0
}

pub fn main(none) i32 {
    target()
}
